language: ruby
rvm:
  - 2.5.0


services:
  - postgresql

before_install:
- export TZ='Europe/London'

before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate

script:
  - bundle exec rspec

deploy:
provider: heroku
api_key:
  secure: "c89107f5-4c7c-4d0a-995d-75bdaa6d41ce"
on:
    all_branches: true
run: "rake db:migrate"